### ISSUE TITLE
Previous options get back after starting debugging

### ISSUE THREAD

**Issue by hellg1** [JetBrains/EzArgs#10]
Version: 1.0.7

STR

1. Write -LOG in EZ Args Combobox
2. Start your game in DebugGame Editor, wait until it is loaded, then close Unreal Editor
3. Erase -LOG option and start debugging again
4. Trigger any breakpoint --> Observe -LOG option got back in combobox again

**Comment by Shenjoku** [comment]
I have a fix for this in my pull request FYI. I don't know how to get it approved though. It's been sitting there for almost a month with no replies.

**Comment by Shenjoku** [comment]
This issue should be fixed with the latest 1.0.15 version. Tried it myself and it works great :D
