### ISSUE TITLE
Combo box ends up being larger than window

### ISSUE THREAD

**Issue by sturcotte06** [JetBrains/EzArgs#15]
I believe that the combo box is as large as the largest command line in the combo box. It makes the combo box insanely large and unmodifiable when a past command (e.g. ue4 cooking commandlet) is very long.

**Comment by YunHsiao** [comment]
Same here, I have to disable the extension for now just for this. It would be nice if we could just manually adjust the input box length.

**Comment by YunHsiao** [comment]
For anyone with similar problem, just reinstalling the extension won't clear the history, you can deleting the `.idea` folder at the same directory as you solution file, or specifically, they are stored as `ezargs.argumentsList` property inside the `workspace.xml` file.

**Comment by Shenjoku** [comment]
I have a fix for this in my pull request FYI. I don't know how to get it approved though. It's been sitting there for almost a month with no replies.

**Comment by Shenjoku** [comment]
This issue should be fixed with the latest 1.0.15 version. Tried it myself and it works great :D
