### ISSUE TITLE
Adding a path to the map as an argument doesn't make the editor start with this map

### ISSUE THREAD

**Issue by MothDoctor** [JetBrains/EzArgs#2]
Works great for me, except for one thing. Adding a path to the map as an argument doesn't make the editor start with this map... The editor starts with opening the default editor map.

https://docs.unrealengine.com/en-US/ProductionPipelines/CommandLineArguments/index.html

**Comment by DecoyRS** [comment]
Hello @MothDoctor 
Sorry for the late response, for some reason I wasn't getting notifications for issue in EzArgs plugin.
Anywho, EzArgs plugins is stupidly simple, It'll take arguments from it's input field and will append them to the command line provided by the Run Configuration selected in the Rider for Unreal Engine. And Rider for Unreal Engine uses default generated Run Configurations with preconfigured command line that might be messing with your use case.
As a workaround, would you be so kind to test next things:
* open Run Configurations edit page (press "triangle" button at configurations and select Edit Configurations)
* make copy of configurations that you want to work with
* clear "Program arguments" field in the copy and leave only path to uproject (example `$(ProjectName).uproject`)
* after that, try adding your args in the EzArgs input field

**Comment by MothDoctor** [comment]
@DecoyRS It works perfectly, thanks! :)

Is there a chance that a future version of the plugin wouldn't require this workaround?

**Comment by DecoyRS** [comment]
Looks like it's a problem with the default generated Run Configuration.
It adds "-skipcompile" right after the path to uproject and it messes with your options to load specific map.
Honestly, I don't have a definitive answer, but I'll try to come up with smth

**Comment by MothDoctor** [comment]
Oh my, it works out of the box in the recent plugin version.
Reinstalled system with Rider, clean settings and it "just works" :)
