### ISSUE TITLE
Combobox is resized after updating to 1.0.7 if there was an option saved in previous version

### ISSUE THREAD

**Issue by hellg1** [JetBrains/EzArgs#9]
STR

1. Have a written option(for example, `-LOG`) in EZ Args combobox in any version of plugin below 1.0.7
2. Upgrade EZ Args to 1.0.7, open the same project -->
    ACTUAL: combobox is resized to the smaller size and won't be resized if you type anything. Deleting option and reopening project doesn't help, option still stays in the memory
![image](https://user-images.githubusercontent.com/56997239/145028145-d42d3a0f-0ab5-4039-b1a1-f9b974a35a60.png)

**Comment by DecoyRS** [comment]
Combo box is fixed size now and you can change the size in the settings:
`File | Settings | Tools | EzArgs | Width`
There were just too many issues with auto resizing not fitting on a toolbar >_>
